### ISSUE TITLE
Add installation instructions?

### ISSUE THREAD

**Issue by sendqueery** [viert/go-lame#1]
Hi there! This seems like a super useful library for a project I'm working on that needs to do a bit of wav > mp3 transcoding, but I'm not really sure how to actually use the library?

Even just running `go get "github.com/viert/go-lame"` fails, since it can't find `lame/lame.h`. I'm not familiar with calling code via cgo, so if any additional setup instruction could be provided, it'd be super helpful.

Cheers!

**Comment by sendqueery** [comment]
For anyone reading this in the future, if you just run `brew install lame`, it'll sort the dependency.

**Comment by RobinKamps** [comment]
Under win10 i got the error: `.....ld.exe: cannot find -lmp3lame ....`.
I have tried it with tdm-gcc and ming-gw64 and put the whole lame folder from `https://sourceforge.net/projects/lame/files/lame/3.100/` under all search include folders - but no success.

How to add the lame library to your linker under win10?

under ubuntu i got the lame lib running but the following error:
```
# github.com/viert/lame
/home/...../go/pkg/mod/github.com/viert/lame@v0.0.0-20190823071122-49a063e7d5e6/lame.go:7:10: fatal error: lame/lame.h: No such file or directory
    7 | #include "lame/lame.h"
      |          ^~~~~~~~~~~~~
```
does anyone knows how to solve the compiling issues (especially under win10)?

**Comment by viert** [comment]
Sorry for being silent for so long, mates.

On Ubuntu the building process is easy as hell, you need to install libmp3lame-dev package to get the library and the headers:
```
p.vorobyov@xenial:~/src/go/go-lame$ sudo apt install libmp3lame-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  libmp3lame0
The following NEW packages will be installed:
  libmp3lame-dev libmp3lame0
0 upgraded, 2 newly installed, 0 to remove and 318 not upgraded.
Need to get 269 kB of archives.
After this operation, 816 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://ru.archive.ubuntu.com/ubuntu xenial/universe amd64 libmp3lame0 amd64 3.99.5+repack1-9build1 [127 kB]
Get:2 http://ru.archive.ubuntu.com/ubuntu xenial/universe amd64 libmp3lame-dev amd64 3.99.5+repack1-9build1 [142 kB]
Fetched 269 kB in 0s (368 kB/s)
Selecting previously unselected package libmp3lame0:amd64.
(Reading database ... 155491 files and directories currently installed.)
Preparing to unpack .../libmp3lame0_3.99.5+repack1-9build1_amd64.deb ...
Unpacking libmp3lame0:amd64 (3.99.5+repack1-9build1) ...
Selecting previously unselected package libmp3lame-dev:amd64.
Preparing to unpack .../libmp3lame-dev_3.99.5+repack1-9build1_amd64.deb ...
Unpacking libmp3lame-dev:amd64 (3.99.5+repack1-9build1) ...
Processing triggers for libc-bin (2.23-0ubuntu10) ...
Setting up libmp3lame0:amd64 (3.99.5+repack1-9build1) ...
Setting up libmp3lame-dev:amd64 (3.99.5+repack1-9build1) ...
Processing triggers for libc-bin (2.23-0ubuntu10) ...
p.vorobyov@xenial:~/src/go/go-lame$ go build
p.vorobyov@xenial:~/src/go/go-lame$
```

With win10 I'm going to need some more time to see how it's done on windows.

**Comment by RobinKamps** [comment]
Hey thank you for the very fast response.

unfortunately i need to build this for win - i tried to compile it under win and to cross compile it under ubuntu.
Your answer is correct to build it under ubuntu for linux.
But when i cross compile for win i get the same error as on win itself:

```
GOOS=windows GOARCH=amd64 CGO_ENABLED=1 CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++ go build
# github.com/viert/lame
/usr/bin/x86_64-w64-mingw32-ld: cannot find -lmp3lame
collect2: error: ld returned 1 exit status
````

**Comment by sendqueery** [comment]
It looks like there's a pretty detailed post on the subject that might be helpful: https://dh1tw.de/2019/12/cross-compiling-golang-cgo-projects/

Trying the pacman stuff might also allow you to just build it natively on W10? Worth a shot, at least. :)

**Comment by olup** [comment]
Hey, reviving this issue, on macos I can't build my project using go-lame as it's missing "lame/lame.h". Not familiar with c binding and I did install lame with brew according to the comment on top - not to avail. Any thoughts on where to put the lame source ?

**Comment by olup** [comment]
Actually, I found out : I needed to set the compiler flag so that it could look in the the `bin` and `lib` directory where brew had installed lame.

**Comment by daniel-sullivan** [comment]
> Actually, I found out : I needed to set the compiler flag so that it could look in the the `bin` and `lib` directory where brew had installed lame.

@olup Would you mind sharing the flags you ended up using? (it might help others with this same issue)

**Comment by olup** [comment]
Of course!

So on Ubuntu or macOS intel, all I had to do is install lame.

Ubuntu:

`sudo apt-get install -y libmp3lame-dev`

macOS x86

`brew install lame`

It's because on those two platform, the package manager directory is in the `sysroot` path (the place the compiler will look to find headers and libraries). Unfortunately, brew's install directory on macOS arm is not in the sysroot, so you just have to point it yourself. So after having installed lame with brew, on an M1, I also used environment variables to set the compilers flags:

`export CGO_LDFLAGS="-L/opt/homebrew/opt/lame/lib" ` (for the lib part)
`export CGO_CFLAGS="-I/opt/homebrew/opt/lame/include"` (for the include part)

With those two environment variables set, you should be able to build.

Side note:

I also wanted to *statically* build my program, so that the end user would *not* have to install lame on her mac for the program to work (lame would be "bundled" with my code). Complete static linking seems impossible on macos, so I could not use the `static` flag. By default the compiler will take the dynamic lame lib in `/opt/homebrew/opt/lame/lib`. The trick for me was just to delete the `.dylib` lame file in this directory - the compiler will then take the static library to build. This is a bit of a hack and I think you can point the compiler to the specific lib file, but I could not find how :-)

**Comment by ospaarmann** [comment]
@olup thank you for the solution. It did not work for me however. I'm on an Apple Silicon M1 running Ventura 13.4. I managed to fix the `fatal error: lame/lame.h: No such file or directory` error by creating symlinks to the default search path:

```shell
brew install lame
sudo ln -s /opt/homebrew/opt/lame/include/lame /usr/local/include/lame
sudo ln -s /opt/homebrew/opt/lame/lib/libmp3lame.a /usr/local/lib/libmp3lame.a
```

I hope that helps someone else out there.
